#정상 실행
#spring:
#  h2:
#    console:
#      enabled: true
#  main:
#    allow-circular-references: true
#---
#문제있음
spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  main:
    allow-circular-references: true
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:testdb # 스프링부트 버전 2.0 이상이신분은 필수로 url 지정 하셔야합니다
    data: classpath:data-h2.sql
    #data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false # 스프링부트 2.0 이상부터는 Hibernate의 id의 defualt값 ture로 되어있기에 이부분을 # false로 바꿔주셔야 합니다. 안그러면 에러가 띄용~
